### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by anchormansam** [JMStewart00/bangachain#6]
As an employee of BangAChain
I would like to have 3 different inventories 
so that I can track whats in the store vs online vs event stock

*Need to figure out the best flow

**Comment by JMStewart00** [comment]
@anchormansam working on this bad boy.

**Comment by anchormansam** [comment]
Current iteration is to set field_bin numbers to be hidden from the site but still allow the POS to check out the item.

This Ticket is a work in progress

**Comment by anchormansam** [comment]
Currently fixed with field_bin set to 100 or lower being hidden from website purchase
